name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "envs/**"
      - "modules/**"

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        env: [dev]

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        working-directory: envs/${{ matrix.env }}
        run: terraform init

      - name: Terraform Apply
        working-directory: envs/${{ matrix.env }}
        run: terraform apply -auto-approve
